services:
  # LARAVEL CONTAINER
  laravel: &laravel
    image: fchavarriar/laravel:amd64
    tty: true
    ports:
      - "8000:80"
      - "2222:2222"
    env_file:
      - .env
    environment:
      GIT_REPO: ${LARAVEL_REPO}
      GIT_TOKEN: ${GIT_TOKEN}
    volumes:
      - laravel:/var/www/${LARAVEL_REPO}
    networks:
      - test-laravel
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/fs_ok.lock"]
      interval: 30s
      timeout: 10s
      retries: 3
  # QUEUE CONTAINER
  queue:
    <<: *laravel
    ports: []
    command: ["/opt/scripts/entry-queue.sh"]
    healthcheck:
      test: []
    depends_on:
      laravel:
        condition: service_healthy
  # DATABASE CONTAINER
  database:
    user: root
    container_name: postgres
    image: postgres:latest
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - test-laravel
networks:
  test-laravel:
volumes:
  laravel:
  database:
